woodenwerewolf:
  framework: flask
  url_root: /werewolf
  cmdb_database:
    host: 'localhost'
    database: 'werewolf'
    user: 'root'
    password: '123456'
    charset: 'utf8'
  redis:
    host: 'localhost'
    port: '6379'
    db: 0
